services:

  local_llm_ollama-chat:
    image: ollama/ollama:0.4.0
    ports:
      - 11438:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: local_llm_ollama-chat
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [ gpu ]
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0

  local_llm_ollama-chat-tools:
    image: ollama/ollama:0.4.0
    ports:
      - 11439:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: local_llm_ollama-chat-tool
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [ gpu ]
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
